replicaCount: 1

image:
  repository: docker.io/your-docker-user/payment-service
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8081

env:
  SPRING_PROFILES_ACTIVE: dev

eureka:
  url: http://eureka:8761/eureka/

resources:
  requests: { cpu: 100m, memory: 256Mi }
  limits:   { cpu: 500m, memory: 512Mi }

hpa:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80

ingress:
  enabled: false
  className: nginx
  hosts: []
  tls: []
