apiVersion: v1
kind: Service
metadata:
  name: { include "payment-service.fullname" . }
spec:
  selector: { app: payment-service }
  ports:
    - port: { .Values.service.port }
      targetPort: 8081
      protocol: TCP
      name: http
  type: { .Values.service.type }
