server:
  port: 8888
spring:
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          searchLocations: file:../config-repo
management.endpoints.web.exposure.include: health,info
