apiVersion: v1
kind: Service
metadata:
  name: { include "eureka.fullname" . }
spec:
  selector: { app: eureka }
  ports:
    - port: { .Values.service.port }
      targetPort: 8761
      protocol: TCP
      name: http
  type: { .Values.service.type }
